name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        profile: minimal
    - name: Build for Linux
      run: cargo build --release --target x86_64-unknown-linux-gnu
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:

        upload_url: ${{ github.event.release.upload_url }}

        github_token: ${{ secrets.GITHUB_TOKEN }}

        asset_path: ./target/x86_64-unknown-linux-gnu/release/ore

        asset_name: ore

        asset_content_type: application/octet-stream
